# Generated by Django 2.0.7 on 2018-07-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0002_auto_20180716_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywriting',
            name='backup',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
