# Generated by Django 2.0.7 on 2018-07-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0003_dailywriting_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywriting',
            name='backup',
        ),
    ]
