# Generated by Django 2.0.7 on 2018-07-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0005_dailywriting_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywriting',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
