# Generated by Django 2.0.7 on 2018-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0010_auto_20180802_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcountgoal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
