# Generated by Django 2.0.7 on 2018-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0011_auto_20180802_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywriting',
            name='word_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wordcountgoal',
            name='count',
            field=models.IntegerField(default=100),
        ),
    ]
