# Generated by Django 2.0.7 on 2018-08-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0013_auto_20180802_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyentry',
            options={'verbose_name_plural': 'daily entries'},
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='word_count_goal',
            field=models.IntegerField(default=100),
        ),
    ]
