# Generated by Django 2.0.7 on 2018-08-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0014_auto_20180802_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywriting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordcountgoal',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyWriting',
        ),
        migrations.DeleteModel(
            name='Streak',
        ),
        migrations.DeleteModel(
            name='WordCountGoal',
        ),
    ]
